spring.application.name=RiderService

spring.datasource.url=jdbc:postgresql://ep-spring-flower-b3e8d8a4-pooler.c-4.ap-southeast-1.aws.neon.tech/neondb?
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Ayp2qEeB5jtv
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.database=0